#!/bin/bash

./clean

seed='Li'

mkdir $seed

rm -rf *.schedopt
cp $DDPBATCH/schedopt/archer2-short.schedopt ./

sed -i 's/--nodes=8/--nodes=1/g' *.schedopt
sed -i 's/--array=1-4/--array=1-4/g' *.schedopt
sed -i 's/ncores_per_subjob=128/ncores_per_subjob=4/g' *.schedopt

# test 1
nohup spawn-batch -despawn -command forge -ompnp 4 -es 10 -n 200 -nn 5 -np -q -numpot 256 -s ./$seed/$seed &

# test 2
#nohup spawn-batch -despawn -bakres mv -command forge -ompnp 4 -es 10 -n 200 -nn 5 -np -q -numpot 256 -s ./$seed/$seed &

exit 0
