#!/bin/bash

set -e

./clean

# Copy the schedopt file

schedoptfile="archer2-short.schedopt"
cp ../bin/schedopt/$schedoptfile .


# Run application

#nohup spawn-batch -genjob -despawn -command franks $rcut $nbody $npoly $lowexp $highexp $ntrain $nvalid $ntest $deltae $meanpress $nembed 2> /dev/null

# test 1: good

nohup spawn-batch -genjob -despawn -command "franks 3.75 3 5 2 10 80 10 10 10 0 0 2> /dev/null"
mv jobscript_franks.sh jobscript_franks_test1.sh

# test 2: bad - redirection cannot be passed into spawn batch

#nohup spawn-batch -genjob -despawn -command franks 3.75 3 5 2 10 80 10 10 10 0 0 2> /dev/null
#mv jobscript_franks.sh jobscript_franks_bad1.sh


# Comments
# Note: rediretion cannot be passed into spawn-batch. If you would like to pass the command line with redirections together, please quote the command line. 

exit 0
