#!/bin/bash

./clean

seed='Li'

tar -xvzf Li.tar.gz &>/dev/null

rm -rf *.schedopt
cp $DDPBATCH/schedopt/archer2-short.schedopt .

sed -i 's/--nodes=8/--nodes=2/g' *.schedopt
sed -i 's/--array=1-4/--array=1-1/g' *.schedopt
sed -i 's/ncores_per_subjob=128/ncores_per_subjob=4/g' *.schedopt

# test 1
nohup spawn-batch -despawn -command airss.pl -mpinp 4 -step 0 -seed $seed -max 600 -repose &

# test 2
#nohup spawn-batch -despawn -bakres mv -command airss.pl -mpinp 4 -step 0 -seed $seed -max 600 -repose &

exit 0
