#!/bin/bash

./clean

seed='Li'

tar -xvzf Li.tar.gz &>/dev/null

cp michael.schedopt.example test.schedopt

# test 1
#nohup spawn-batch -despawn -command airss.pl -mpinp 4 -step 0 -seed $seed -max 600 -repose &

# test 2
nohup spawn-batch -despawn -bakres mv -command airss.pl -mpinp 4 -step 0 -seed $seed -max 600 -repose &

exit 0
