#!/bin/bash
    echo '    launching airss ...'

    if [[ ${prand} == true ]]
    then
        spawn-batch  -command airss.pl -max $minima -keep -mpinp $mpinp -press $pressure -pmin $lowpress -prand -repose -nbest $nbest -devmin $deviation -seed $seed &
    else
        spawn-batch  -command airss.pl -max $minima -keep -mpinp $mpinp -press $pressure -repose -nbest $nbest -devmin $deviation -seed $seed &
    fi

    counter=0

    targetrate=10
    targetrate=$waitseconds
    acceptrate=0
    rejects=0
    trials=0
    maxtrials=$(( minima * 100 / targetrate ))

    until [[ $counter -ge $minima || $trials -ge $maxtrials ]]
    do
        sleep 1
        test -f "./STOP" && echo -e '\nstopping chain ..' && ./despawn-batch && exit 0
        counter=`ls $seed-*.res 2> /dev/null | wc -l`
        echo -n -e "\r\033[0K    "$counter" structures"
        if [[ $counter -ge 1 ]]; then
            rejects=$(ls trash/${seed}-*.err 2>/dev/null | wc -l)
            trials=$((counter + rejects))
            acceptrate=$((counter * 100 / trials))
        fi
    done
    echo

    echo "number of trials: $trials"
    echo "acceptance rate: $acceptrate"
    echo "target rate: $targetrate"

    if [[ $counter -lt $minima ]]; then
        deviation=`echo "scale=3;"$deviation"/2.000" | bc -l`
        echo '    deviation bias reduced to: '$deviation
    else
        deviation=`echo "scale=3;"$deviation"*1.618" | bc -l`
        echo '    deviation bias increased to: '$deviation
    fi

    echo '    stopping airss ...'

    ./despawn-batch

    sleep 5

