#!/bin/bash

set -e


function gen_chainbatch_acceptancerate {

<<COMMENT
    Implement the acceptance rate to temper the deviation in 'relaxandjiggle' part
    use waittime as a acceptance rate
COMMENT

    chainbatch="chain-batch"

    echo "generate $chainbatch-acceptancerate ..." 

    ## usage & defaults & get options & check before proceeding
    sed -n '1,/^## generate data by relaxation of random structures using repose/p' $chainbatch | head -n -1 \
    > $chainbatch.temp

    ## relaxandjiggle: generate data by relaxation of random structures using repose, and computing energy using castep
    sed -n '/^## generate data by relaxation of random structures using repose/,/^}/p' $chainbatch \
        | sed -n '/^## generate data by relaxation of random structures using repose/,/^function/p' \
        >> $chainbatch.temp
    echo >> $chainbatch.temp

    cat ./relaxandjiggle_airss_acceptancerate | tail -n +2 >> $chainbatch.temp

    sed -n '/^## generate data by relaxation of random structures using repose/,/^}/p' $chainbatch \
        | sed -n '/shaking structures/,/^}/p' \
        >> $chainbatch.temp
    echo >> $chainbatch.temp

    sed -n '/^## construct ensemble potentials/,$p' $chainbatch \
    >> $chainbatch.temp
    
    chmod 777 $chainbatch.temp
    mv $chainbatch.temp $chainbatch-deviationbias

    echo -e "done\n"
}


###############################################################33
# main
###############################################################33

rm -f ./chain-batch
cp $(which chain-batch) ./ 

gen_chainbatch_acceptancerate

rm -f ./chain-batch
