#!/bin/bash

set -e

if [ $# -ne 1 ]; then
    echo 1>&2 "Usage: prim"
    exit 127
fi

# Get arguments

jobid=$1
numpot=$2

prefix='.spawnpids'
jids=${jobid}
tsec_start=$(date +%s)


# check the number of potential generated (./$seed/*.ddp files)'

counter=0
counterddp=0

until [[ $counter -ge $numpot || $counterddp -ge $numpot ]]
do
    sleep 1

    counter=$(grep "testing:   testing" ${seed}/*.out | wc -l)
    counterddp=$(ls ${seed}/*.ddp | wc -l)

    t_check=$(date +%Y-%m-%d\ %H:%M:%S)
    tsec_check=$(date +%s)
    tsec_run=$((${tsec_check} - ${tsec_start}))
    rt_h=$(( ${tsec_run}/3600 ))
    rt_m=$(( (${tsec_run}/60) - (${rt_h}*60) ))
    rt_s=$(( ${tsec_run} - (${tsec_run}/60)*60 ))

    sed -i "/check_time/d"                                     ${prefix}.${jids}
    sed -i "/run_time/d"                                       ${prefix}.${jids}
    sed -i "/no. potentials/d"                                 ${prefix}.${jids}
    echo "check_time:         ${t_check}"                   >> ${prefix}.${jids}
    echo "run_time:           ${rt_h}:${rt_m}:${rt_s}"      >> ${prefix}.${jids}
    echo "no. potentials:     ${counterddp}"                >> ${prefix}.${jids}
done

sleep 5

# Create a DONE file to signal that the job is done

touch DONE_${jobid}

exit 0
