#!/bin/bash

./clean

seed='Li'

rm -rf *.schedopt
cp $DDPBATCH/schedopt/michael-A.schedopt .
#cp $DDPBATCH/schedopt/michael-K.schedopt .

# test 1
#nohup spawn-batch -despawn -command airss.pl -mpinp 4 -step 0 -seed $seed -max 600 &

# test 2
nohup spawn-batch -bakres mv -despawn -command airss.pl -mpinp 4 -step 0 -seed $seed -max 600 &

exit 0
