#!/bin/bash

./clean

seed='Li'

rm -rf *.schedopt
cp $DDPBATCH/schedopt/archer2-short.schedopt ./

sed -i 's/--nodes=8/--nodes=1/g' *.schedopt
sed -i 's/--array=1-4/--array=1-4/g' *.schedopt
sed -i 's/ncores_per_subjob=128/ncores_per_subjob=4/g' *.schedopt

# test 1 - no embedding
nohup chain-batch -M 4 -f 100 -m 10 -n 5 -r 5 -P 5 -F 256 -d 0.1 -w 100 -s Li &
#nohup chain-batch -M 4 -f 100 -m 10 -n 5 -r 5 -P 5 -F 256 -d 0.1 -u 3 -w 100 -s Li &


exit 0
