#!/bin/bash

./clean

seed='Li'

rm -rf *.schedopt
cp ../../bin/schedopt/archer2-short.schedopt ./

# test 1
nohup chain-batch -M 4 -f 100 -m 10 -n 5 -r 5 -P 5 -F 256 -d 0.1 -w 100 -s Li &
#nohup chain-batch -M 4 -f 100 -m 10 -n 5 -r 5 -P 5 -F 256 -d 0.1 -u 3 -w 100 -s Li &


exit 0
